<?php

declare(strict_types=1);

namespace App\Infrastructure\Service;

use App\Domain\Entity\JournalEntry;
use App\Domain\Enum\JournalEntryType;
use App\Domain\Enum\TransactionType;
use App\Domain\Exception\DomainException;
use App\Domain\Repository\CustomerLedgerRepository;
use App\Domain\Repository\GeneralLedgerRepository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * ManualJournalService — posts accountant-authored journals.
 *
 * Every other journal in CreditX is system-generated by a posting
 * service (disbursement, repayment, penalty, write-off, provision,
 * period-close, reversal). This service is the one entry point a human
 * accountant uses to record everything those flows don't cover:
 * operating expenses (salaries, rent, utilities), capital injections,
 * fixed-asset purchases, depreciation, tax accruals, and correcting
 * entries.
 *
 * It deliberately reuses LedgerService::postJournal — the same balanced-
 * posting helper the automated services use — so manual entries get the
 * identical DR==CR validation, JournalEntry header, and audit trail. The
 * only thing this service adds on top is resolving the GL/sub-ledger
 * references from the raw IDs an HTTP client supplies and guarding the
 * target period.
 */
final class ManualJournalService
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly GeneralLedgerRepository $glRepo,
        private readonly CustomerLedgerRepository $clRepo,
        private readonly PeriodGuardService $periodGuard,
        private readonly LedgerService $ledger,
    ) {}

    /**
     * Post a balanced manual journal.
     *
     * @param string      $postingDate YYYY-MM-DD effective date
     * @param string      $narration   journal-level description
     * @param string|null $reference   optional external reference
     * @param array<int, array<string, mixed>> $lines each: {
     *     gl_id: string (required),
     *     type: 'DR'|'CR' (required),
     *     amount: string|float positive (required),
     *     narration?: string,
     *     reference?: string,
     *     customer_ledger_id?: string
     * }
     * @param string|null $userId user posting the entry
     *
     * @throws DomainException on validation failure (bad GL, closed
     *         period, fewer than two lines, unbalanced — the last comes
     *         from postJournal). Callers translate this to a 400/422.
     */
    public function post(
        string $postingDate,
        string $narration,
        ?string $reference,
        array $lines,
        ?string $userId,
    ): JournalEntry {
        if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $postingDate)) {
            throw new DomainException('posting_date must be a valid YYYY-MM-DD date.');
        }
        // Refuse to post into a closed accounting period — same guard the
        // automated posting services apply.
        $this->periodGuard->assertDateOpen($postingDate);

        if (count($lines) < 2) {
            throw new DomainException('A manual journal must have at least two lines (one debit and one credit).');
        }

        // Resolve raw IDs into entities and normalise into the line shape
        // postJournal expects. We validate everything BEFORE opening the
        // transaction so a bad reference fails cheaply.
        $built = [];
        $sawDebit = false;
        $sawCredit = false;
        foreach ($lines as $i => $line) {
            $human = $i + 1;

            $glId = isset($line['gl_id']) ? (string) $line['gl_id'] : '';
            if ($glId === '') {
                throw new DomainException("Line {$human}: gl_id is required.");
            }
            $gl = $this->glRepo->find($glId);
            if ($gl === null) {
                throw new DomainException("Line {$human}: GL account {$glId} not found.");
            }
            if (!$gl->isActive()) {
                throw new DomainException("Line {$human}: GL account {$gl->getAccountCode()} is inactive and cannot be posted to.");
            }

            $typeRaw = strtoupper(trim((string) ($line['type'] ?? '')));
            $type = TransactionType::tryFrom($typeRaw);
            if ($type === null) {
                throw new DomainException("Line {$human}: type must be 'DR' or 'CR' (got '{$typeRaw}').");
            }

            $amount = isset($line['amount']) ? (string) $line['amount'] : '';
            if (!preg_match('/^\d+(\.\d{1,2})?$/', $amount) || bccomp($amount, '0.00', 2) <= 0) {
                throw new DomainException("Line {$human}: amount must be a positive number.");
            }

            $lineNarration = trim((string) ($line['narration'] ?? '')) ?: $narration;

            $row = [
                'gl'        => $gl,
                'type'      => $type,
                'amount'    => $amount,
                'narration' => $lineNarration,
            ];

            if (!empty($line['reference'])) {
                $row['reference'] = (string) $line['reference'];
            }

            // Optional sub-ledger line (e.g. a manual adjustment against a
            // specific customer's deposit or loan balance).
            if (!empty($line['customer_ledger_id'])) {
                $cl = $this->clRepo->find((string) $line['customer_ledger_id']);
                if ($cl === null) {
                    throw new DomainException("Line {$human}: customer ledger {$line['customer_ledger_id']} not found.");
                }
                $row['customerLedger'] = $cl;
            }

            if ($type === TransactionType::DR) {
                $sawDebit = true;
            } else {
                $sawCredit = true;
            }

            $built[] = $row;
        }

        if (!$sawDebit || !$sawCredit) {
            throw new DomainException('A manual journal must contain at least one debit and one credit line.');
        }

        // postJournal flushes internally, so wrap in an explicit
        // transaction the same way the automated posting services do.
        $this->em->beginTransaction();
        try {
            $journal = $this->ledger->postJournal(
                entryType: JournalEntryType::MANUAL,
                postingDate: $postingDate,
                narration: $narration,
                postedBy: $userId,
                lines: $built,
                reference: $reference,
            );
            $this->em->commit();

            return $journal;
        } catch (\Throwable $e) {
            $this->em->rollback();
            throw $e;
        }
    }
}
